#!/usr/bin/python3

# raise exception value
def raise_exception_msg(message=""):
    try:
        return mes
    except NameError:
        print(message)
